version: '3.8'

services:
  api:
    build:
      context: .
      target: development
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - ./src:/usr/src/app/src
      - ./bin:/usr/src/app/bin
      - ${PWD}/package.json:/usr/src/app/package.json
    ports:
      - 3000:3000
      # Debug Port 
      - 9234:9229
    command: npm run start:debug
    environment: 
      DATABASE_URL: postgres://username:password@postgres:5432/db
      OPENAI_API_KEY: ${OPENAI_API_KEY_PERSONAL}
      OPENAI_MODEL: 'gpt-4-turbo-preview'
      OPENAI_TEMPERATURE: 0.7
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: