openapi: 3.0.0
paths:
  /v1:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
  /v1/memory:
    get:
      operationId: MemoryV1Controller_getAllMemories
      summary: Get All Memories
      parameters: []
      responses:
        "200":
          description: ""
      tags: &a1
        - Memory
  /v1/memory/{uuid}:
    delete:
      operationId: MemoryV1Controller_deleteMemory
      summary: Delete Memory
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a1
info:
  title: Raven
  description: ""
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas: {}
