openapi: 3.0.0
paths:
  /v1:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
  /v1/memories:
    get:
      operationId: MemoryV1Controller_getAllMemories
      summary: Get All Memories
      parameters: []
      responses:
        "200":
          description: ""
      tags: &a1
        - Memory
  /v1/memories/{uuid}:
    delete:
      operationId: MemoryV1Controller_deleteMemory
      summary: Delete Memory
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a1
  /v1/memories/articles:
    get:
      operationId: ArticleV1Controller_getAllMemories
      summary: Get All Articles
      parameters: []
      responses:
        "200":
          description: " A list of the user's memories."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleDto"
      tags: &a2
        - Article
    post:
      operationId: ArticleV1Controller_postMemory
      summary: Create Memory
      description: Uses AI to generate a memory from a url.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArticlePostDto"
      responses:
        "201":
          description: The memory was created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleDto"
      tags: *a2
  /v1/memories/articles/auto:
    post:
      operationId: ArticleV1Controller_postMemoryAuto
      summary: Auto Create Memory
      description: Uses AI to generate a memory from a url.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AutoMemoryPostDto"
      responses:
        "201":
          description: The memory was created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleDto"
      tags: *a2
  /v1/memories/articles/{uuid}:
    delete:
      operationId: ArticleV1Controller_deleteMemory
      summary: Delete article
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a2
  /v1/test/users:
    post:
      operationId: UsersTestV1Controller_registerTestUser
      summary: ""
      description: Register a test user
      parameters: []
      responses:
        "201":
          description: The test user has been registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestUserDto"
      tags: &a3
        - Test
  /v1/test/users/{uuid}:
    delete:
      operationId: UsersTestV1Controller_deleteTestUser
      summary: ""
      description: Delete a test user
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a3
info:
  title: Raven
  description: ""
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    ArticleDto:
      type: object
      properties:
        uuid:
          type: string
          example: ac47bd67-242b-4d0c-929c-a3127b9c5232
          description: The unique identifier of the article.
        title:
          type: string
          example: A raven's memories are for the future
          description: The title of the article
        createdAt:
          format: date-time
          type: string
          example: 2021-08-01T00:00:00.000Z
          description: The date the article was created
        url:
          type: string
          example: https://pubmed.ncbi.nlm.nih.gov/28706023/
          description: The url to the article
        summary:
          type: string
          example: The summary of the article
          description: The summary of the article
        author:
          type: string
          example: Markus Boeckle, Nicola S Clayton
          description: The author of the article
      required:
        - uuid
        - title
        - createdAt
        - url
        - summary
        - author
    AutoMemoryPostDto:
      type: object
      properties:
        url:
          type: string
          example: https://pubmed.ncbi.nlm.nih.gov/15114002/
          description: The url to the memory
      required:
        - url
    ArticlePostDto:
      type: object
      properties:
        url:
          type: string
          example: https://pubmed.ncbi.nlm.nih.gov/15114002/
          description: The url to the memory
        title:
          type: string
          example: The title of the memory
          description: The title of the memory
        summary:
          type: string
          example: The summary of the memory
          description: The summary of the memory
        author:
          type: string
          example: Jane Doe
          description: The author of the memory
      required:
        - url
        - title
        - summary
        - author
    TestUserDto:
      type: object
      properties:
        email:
          type: string
          example: test@test.com
          description: The email of the test user
        apiKey:
          type: string
          example: aad91f3e-7d83-429e-8acd-c44c177f3933
          description: The apiKey of the test user
        uuid:
          type: string
          example: aad91f3e-7d83-429e-8acd-c44c177f3933
          description: The uuid of the test user
      required:
        - email
        - apiKey
        - uuid
