version: '3'
tasks:
  build:
    desc: 'Build the application'
    cmds:
      - docker compose build
      - echo "Success!"
  restart:
    aliases: ['r']
    desc: 'Restart the application'
    cmds:
      - docker compose up -d
      - echo "Success!"
  start:
    desc: 'Start the application'
    cmds:
      - docker compose up -d
      - echo "Success!"
  schemaCheck:
    desc: 'Check the schema'
    cmds:
      - docker-compose exec api npm run typeorm -- schema:log
  ssh:
    desc: 'SSH into the container'
    cmds:
      - docker-compose exec api sh
  connectDb:
    aliases: ['cdb']
    desc: 'Connect to the database'
    cmds:
      - docker compose exec postgres psql postgres://username:password@postgres:5432/db
  createUser:
    desc: 'Create a new user'
    cmds:
      - docker-compose exec postgres psql postgres://username:password@postgres:5432/db -c \
        "INSERT INTO \"user\"(api_key, email) VALUES(uuid_generate_v4(), 'test@test.com') RETURNING *"
